# Generated by Django 4.2.2 on 2023-07-02 09:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')],
                        default='PENDING',
                        max_length=10,
                    ),
                ),
                ('sync', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'store_order',
            },
        ),
    ]
